### ISSUE TITLE
Context Cookie setting(s) incompatible with GatewayManager

### ISSUE THREAD

**Issue by JimKillock** [bertoost/MODX-GatewayManager#11]
Context settings such as session_cookie_domain aren't handled by subdomains managed by GatewayManager.

See: http://forums.modx.com/thread/91099/session-cookie-setting-not-doing-anything

"gateway manager is a plugin and has to switch to a context, but the session is always loaded by the default context loaded in the index.php (web). In order to use a different session for your subdomain, you would need to modify the index.php and have it handle the initialization of the correct subdomain context in the first place."

It'd be handy to either have an example index.php which could deal with this, or maybe find some way with the MODX devs to make them play nicer together.

**Comment by bertoost** [comment]
Will look at it, but don't know if this is a GM problem or a generic session/cookie issue

**Comment by bertoost** [comment]
Not a GM issue as I expected. See https://rtfm.modx.com/revolution/2.x/administering-your-site/settings/system-settings/session_cookie_domain for more details
