### ISSUE TITLE
Different start_site definitions in the context and gateway brakes the website

### ISSUE THREAD

**Issue by IamNeo1** [bertoost/MODX-GatewayManager#13]
When the context and the gateway sets different start sites the website brakes. I can’t click the navigation to watch the hole site. The addon overwrites the context setting and the start site definition from the gateway will be used. The Website starts with the defined start site from the gateway. When I delete the start site setting from the gateway the context setting will be used and the website works.

**Comment by bertoost** [comment]
Fixed in the next update. Redirect stuff will only be triggered when trying to reach the homepage URL. Like "/"  or "/index.html"  etc.
