### ISSUE TITLE
Defined context is ignored in the start site field in existing gateway

### ISSUE THREAD

**Issue by IamNeo1** [bertoost/MODX-GatewayManager#14]
When I create a new gateway only the sites from the choosen context appears. When I want to change the start site later the Gateway Manager shows the first 20 sites of every site of every context, sorted alphabetically, without a chance to see the other sites. You can only type in the side-id. The gateway manager loads the side from the id.

**Comment by bertoost** [comment]
Re-open and clearify more if the problem still exists. Don't know what you mean.
