### ISSUE TITLE
FURLS

### ISSUE THREAD

**Issue by 4ntz** [bertoost/MODX-GatewayManager#15]
This is obviously not a bug but my lack of knowledge - maybe you can assist me. I have set up my context settings and everything works until the FURLS come into play. I just don't know how to configure the .htaccess file to get my two domains working with FURLS - my 2nd domain keeps redirecting to my 1st domain. Maybe you could post an example .htaccess file? That would be awesome!

**Comment by bertoost** [comment]
In MODX's htaccess.default you'll find this lines;

```
# The Friendly URLs part
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php?q=$1 [L,QSA]
```

This will activate the friendly urls to work. Start with this and bring back your htaccess to their defaults. Then start adding the other rewrite lines again. And make sure it worked before, then see where it fails and what you're doing wrong. If you can't find, please post  your htaccess contents :-)
