### ISSUE TITLE
Gateway Manager and Instructions are different..

### ISSUE THREAD

**Issue by pixelstuff** [bertoost/MODX-GatewayManager#16]
When I added a domain to Gateway Manager it offered to create the context settings. The auto-add feature created these settings:

base_url
http_host
site_url

The documentation here https://rtfm.modx.com/extras/revo/gatewaymanager says to add:

http_host
site_url
site_start

(So is base_url wrong or is site_start wrong, or do I need to add site_start in addition to the rest.)

**Comment by bertoost** [comment]
In fact; "base_url"  setting should not be needed, since Gateway Manager is hostname based, this is always "/"  as configured in the base config setup of MODX.

Also; site_start isn't necessary. MODX finds the first page in the context-tree to start with.

Will refactor Gateway Manager soon!

**Comment by bertoost** [comment]
Fixed in upcoming update
