### ISSUE TITLE
Gateway Manager not subdomain aware?

### ISSUE THREAD

**Issue by pixelstuff** [bertoost/MODX-GatewayManager#17]
Not sure if this is a Gateway Manager bug or problem with site configuration.

If I add site.com to Gateway Manager then browse to www.site.com (with the WWW), Gateway Manager lets www.site.com go to my default context. Or I can do the opposite and add www.site.com to GM which then lets site.com go to the default context.

If I try to add both variations to GM, it appears to allow it, but doesn't make any changes in my secondary context settings. Whichever one I created first is the only one that works.

**Comment by bertoost** [comment]
Don't know exactly. But you should make sure that www. and non-www variants staying in the URL address bar of the browser, then GM is capeable to capture them and forward the context of your choice in the MODX GM manager pages.

When the URL/domain isn't correctly in the address bar, it's not possible for GM to route them.

This is called domain alias.

The best you can do;
1. determine which is the one, with or without www prefix.
2. make htaccess (or NginX) rules to rewrite the other one
3. configure GM to handle the right one to the right context.

Hope this helps. Let me know.
