### ISSUE TITLE
call to get() on a non-object

### ISSUE THREAD

**Issue by mohicanlove** [bertoost/MODX-GatewayManager#5]
I'm running modx 2.2.8.
I'm trying to convert my current context/subdomain setup from using separate index.php and config.core.php files to using the gateway manager.
I'm getting this same error both locally and on a modxcloud account. 

```
PHP Fatal error:  Call to a member function get() on a non-object in /modx/core/cache/includes/elements/modplugin/9.include.cache.php on line 37
```
It looks like it's dying when it gets to this block in the plugin:
``` php
// get the context from the setupped domain
    $context = $domain->getOne('Context');
    $domContext = $context->get('key');
    $sameContext = ($currContext == $domContext) ? true : false;
```

The host name is correct, and it is loading a context into $domain, but $domain->getOne('Context'); is returning null.

The subdomain set for the http_host variable in the context matches the one set in the gateway config, I can't figure out why it isn't working.

**Comment by tpxtron** [comment]
Same here on a fresh installed ModX with Gateway Manager Plugin. Domains without "-" characters work fine.

Already forked to fix the issue myself but couldn't find the bug. :-(
